apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
spec:
  selector:
    matchLabels:
      app: webapi-app
  template:
    metadata:
      labels:
        app: webapi-app
    spec:
      containers:
      - name: webapi-app
        image: docker.io/filterniels/deploy-options-webapi:latest
        env:
        - name: LuckyNumberService__ApiUrl
          value: http://10.0.46.96/ #lucky-number-app.default #todo
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          value: InstrumentationKey=1e881e38-f95a-40ac-b973-949bff490c23;IngestionEndpoint=https://westus2-2.in.applicationinsights.azure.com/;LiveEndpoint=https://westus2.livediagnostics.monitor.azure.com/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapi-app
spec:
  type: LoadBalancer
  selector:
    app: webapi-app
  ports:
  - port: 80
    targetPort: 80