apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-app
spec:
  selector:
    matchLabels:
      app: front-end-app
  template:
    metadata:
      labels:
        app: front-end-app
    spec:
      containers:
      - name: front-end-app
        image: docker.io/filterniels/deploy-options-angular:latest
        imagePullPolicy: Always
        env:
        - name: API_URL
          value: webapi-app.svc.cluster.local  #http://20.124.161.128/ 
        - name: APPLICATIONINSIGHTS_INSTRUMENTATION_KEY
          value: 1e881e38-f95a-40ac-b973-949bff490c23
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-app
spec:
  type: LoadBalancer
  selector:
    app: front-end-app
  ports:
  - port: 80
    targetPort: 80