# This is a basic workflow to help you get started with Actions

name: build images and deploy to DockerHub

on:
  workflow_run:
    workflows: ["Deploy Containers"]
    types:
      - completed
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
  
      - name: Az Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy infrastructure with bicep
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: 490eb18c-41ab-4b43-bfe8-334a4d8c8a33
          resourceGroupName: ContainerAppDeployment
          template: ./main.bicep
          deploymentMode: Incremental
          failOnStdErr: false #sucks to have to do this, but in container app incorrectly fails validation (due to warning), causing the workflow to bomb out
          
  deploy-luckynum:
    runs-on: ubuntu-latest
    needs: infrastructure

    steps:
      - name: Az Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create container app revision
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.0-py2.py3-none-any.whl --yes
            echo "Starting Deploying"
            az containerapp update -g ContainerAppDeployment -n deploy-options-luckynum -i docker.io/filterniels/deploy-options-luckynum:latest --yaml ./LuckyNumberGenerator/container-app.yml

  deploy-webapi:
    runs-on: ubuntu-latest
    needs: infrastructure

    steps:
      - name: Az Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create container app revision
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.0-py2.py3-none-any.whl --yes
            echo "Starting Deploying"
            az containerapp update -g ContainerAppDeployment -n deploy-options-webapi -i docker.io/filterniels/deploy-options-webapi:latest --yaml ./WebApi/container-app.yml

  deploy-angular:
    runs-on: ubuntu-latest
    needs: infrastructure

    steps:
      - name: Az Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create container app revision
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.0-py2.py3-none-any.whl --yes
            echo "Starting Deploying"
            az containerapp update -g ContainerAppDeployment -n deploy-options-angular -i docker.io/filterniels/deploy-options-angular:latest --yaml ./Angular/container-app.yml
