# This is a basic workflow to help you get started with Actions

name: build images and deploy to DockerHub

on:
  push:
    branches: [ * ]
  pull_request:
    branches: [ * ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-luckynum:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
                  
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: LuckyNumberGenerator
          file: LuckyNumberGenerator/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/deploy-options-luckynum:latest
                
      - name: Az Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

  deploy-webapi:
    runs-on: ubuntu-latest
    needs: infrastructure

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: WebApi
          file: WebApi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/deploy-options-webapi:latest
          
      - name: Az Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
  deploy-angular:
    runs-on: ubuntu-latest
    needs: infrastructure

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
                  
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: Angular
          file: Angular/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/deploy-options-angular:latest
          
      - name: Az Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
