name: Deploy AKS Infrastructure

on:
  workflow_dispatch:

jobs:

  infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
  
      - name: Az Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy infrastructure with bicep
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: 490eb18c-41ab-4b43-bfe8-334a4d8c8a33
          resourceGroupName: arm-deployment-dev
          template: ./aks.bicep
          deploymentMode: Incremental
          failOnStdErr: false